# World and region configuration
worlds:
  world:                # The name of your Minecraft world (e.g., "world", "world_nether")
    region: "guppy_shrine"  # The WorldGuard region ID where offerings can be made

# Valid offering items
offerings:
  DIAMOND:             # Minecraft material name (must be exact)
    chance: 100        # This value determines how common this offering type is
                      # Higher numbers mean more common (relative to other offerings)

# Rewards configuration
rewards:
  common_reward:       # Unique identifier for the reward
    name: "Common Reward"   # Display name shown to players
    command: "give {player} diamond 1"  # Command executed when reward is given
                                       # {player} is replaced with the player's name
    chance: 70        # Probability weight for this reward
                      # Higher numbers mean more likely to be chosen

# Sound effects
sounds:
  accepted-offering:   # Sound played when an offering is accepted
    sound: entity.player.levelup  # Minecraft sound name
    volume: 1.0       # Sound volume (0.0 to 1.0)
    pitch: 1.0        # Sound pitch (0.5 to 2.0)
  rejected-offering:
    sound: block.anvil.land
    volume: 1.0
    pitch: 0.5
